// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupQvdEuMD_fn1aAqiNZuPm0hnmq84pzY',
    appId: '1:491813809201:web:8a08f0cfd556b87188f910',
    messagingSenderId: '491813809201',
    projectId: 'todo-app-modern',
    authDomain: 'todo-app-modern.firebaseapp.com',
    storageBucket: 'todo-app-modern.appspot.com',
    measurementId: 'G-XZSN0QHZ42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCETppAVRFD_oAbJuGYKZbX75EvtGW2BYA',
    appId: '1:491813809201:android:14560c842cd81f8c88f910',
    messagingSenderId: '491813809201',
    projectId: 'todo-app-modern',
    storageBucket: 'todo-app-modern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWXW0ee5FaTxfJOtOIwzGWW7YizfB5SGI',
    appId: '1:491813809201:ios:6a9be854cc41500888f910',
    messagingSenderId: '491813809201',
    projectId: 'todo-app-modern',
    storageBucket: 'todo-app-modern.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWXW0ee5FaTxfJOtOIwzGWW7YizfB5SGI',
    appId: '1:491813809201:ios:12dd112d2788e76d88f910',
    messagingSenderId: '491813809201',
    projectId: 'todo-app-modern',
    storageBucket: 'todo-app-modern.appspot.com',
    iosBundleId: 'com.example.todoApplication.RunnerTests',
  );
}
